# Exclude temporary files
AllCops:
  TargetRubyVersion: 2.4
  DefaultFormatter: fuubar
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
  - tmp/**/*
  - bin/*

# The enforced style doesn’t match Vim’s defaults
Layout/AlignParameters:
  Enabled: false

# Need to be skipped for >-> usage
Layout/SpaceAroundOperators:
  Enabled: false

# It’s quite readable when we know what we are doing
Lint/AssignmentInCondition:
  Enabled: false

Lint/Debugger:
  Exclude:
  - examples/*

# No need to handle LoadError in Rakefile
Lint/HandleExceptions:
  Exclude:
  - Rakefile

# Allow rom-sql
Naming/FileName:
  Enabled: false

# gemspec is a special snowflake
Metrics/LineLength:
  Max: 256

Metrics/BlockLength:
  Exclude:
  - spec/**/*_spec.rb

# UTF-8 is perfectly fine in comments
Style/AsciiComments:
  Enabled: false

# Allow using braces for value-returning blocks
Style/BlockDelimiters:
  Enabled: false

# Documentation checked by Inch CI
Style/Documentation:
  Enabled: false

# Early returns have their vices
Style/GuardClause:
  Enabled: false

# Need to be skipped for >-> usage
Style/Lambda:
  Enabled: false

Style/LambdaCall:
  EnforcedStyle: braces

# Multiline block chains are ok
Style/MultilineBlockChain:
  Enabled: false

# Don’t introduce semantic fail/raise distinction
Style/SignalException:
  EnforcedStyle: only_raise

# Accept both single and double quotes
Style/StringLiterals:
  Enabled: false

# Allow def self.foo; @foo; end
Style/TrivialAccessors:
  Enabled: false

# Generated by `rubocop --auto-gen-config`
inherit_from: .rubocop_todo.yml
