language: ruby
sudo: false
cache: bundler
bundler_args: --without ide
script: "bin/rake ci"
rvm:
  - 2.4
  - ruby-head
env:
  global:
    - CODECLIMATE_REPO_TOKEN=d284024edac5ef6b2f4b7d4a85505d192433ea269824c54592876999f0efce47
matrix:
  allow_failures:
    - rvm: ruby-head
